### ISSUE TITLE
Tiny MotionNet

### ISSUE THREAD

**Issue by mariankyoussef** [bryanyzhu/Hidden-Two-Stream#14]
Hello, thank you for the great work!
I want to ask whether the available MotionNet model is Tiny MotionNet or not, and if not, do you have it available elsewhere ready to be used for fine-tuning?

**Comment by bryanyzhu** [comment]
Hi, thanks for your interest. No, it is the original MotionNet, not the tiny MotionNet. I don't have the pre-trained model right now. Sorry about that. I don't work on this project for the past several months, and will start to rewrite it in Pytorch during the summer time. I will release the pre-trained tiny MotionNet in Pytorch by then. But if you need it right now, I suggest you train it yourself. It won't take long.

**Comment by mariankyoussef** [comment]
Thank you for your speedy reply. Do you have the script for the model or any further details about it? Thanks in advance.

**Comment by bryanyzhu** [comment]
Due to a system crash (gpu driver issue), I don't have anything left for tiny MotionNet experiment. So that is why I don't upload its pretrained model to google drive. But it should be easy to write the training prototxt file based on what I wrote for MotionNet. You just need to delete a lot of layers. Sorry about that.

**Comment by mariankyoussef** [comment]
No worries at all.. thank you so much!

**Comment by mariankyoussef** [comment]
Hello again, did you manage to finish the pretraied tiny MotionNet in pytorch?

**Comment by bryanyzhu** [comment]
Hi, thanks for asking. Yes, I do finish the pretrained tiny MotionNet in PyTorch. 

But at this moment, this paper is still not accepted, which is quite frustrating to us. We have decided not to release the updated model until the paper is accepted. Sorry about the long waiting.

**Comment by mariankyoussef** [comment]
Thanks for your reply. Do you have an idea how long might this take?

On Jun 20, 2018 12:39 AM, "Yi Zhu" <notifications@github.com> wrote:

Hi, thanks for asking. Yes, I do finish the pretrained tiny MotionNet in
PyTorch.

But at this moment, this paper is still not accepted, which is quite
frustrating to us. We have decided not to release the updated model until
the paper is accepted. Sorry about the long waiting.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bryanyzhu/Hidden-Two-Stream/issues/14#issuecomment-398568476>,
or mute the thread

**Comment by bryanyzhu** [comment]
It is in a journal submission now, I have no clue either. I hope it is in the near future, but I can't guarantee anything. 

There are many good repos computing flow in PyTorch, like [this one](https://github.com/ClementPinard/FlowNetPytorch) and [this one](https://github.com/NVIDIA/flownet2-pytorch). If you are in a hurry, you can refer to these two repos and write your own. I also write my own code based on these two repos.

**Comment by mariankyoussef** [comment]
Okay I'll check them. I can't thank you enough for your help.

**Comment by bryanyzhu** [comment]
No problem, it is my pleasure.
