### ISSUE TITLE
Need detailed tutorial steps on implementation 

### ISSUE THREAD

**Issue by adimurthi** [bryanyzhu/Hidden-Two-Stream#15]
Hello Yi Zhu,
                     I am trying to implement this code but i am getting errors. could you just please send me more detailed steps on implementation. thank you

**Comment by bryanyzhu** [comment]
Hi, thanks for your interest in our work. But I think my README is detailed enough. If you have any questions, you can read the paper for more details. If you have any specific questions about the implementation, such as how to train, how to test, how to prepare and load the data, you can open new issues. I am happy to answer them.
