### ISSUE TITLE
getting error during training

### ISSUE THREAD

**Issue by adimurthi** [bryanyzhu/Hidden-Two-Stream#16]
I followed the steps given for training like changing the frame in train_rgb_split1.txt and val_rgb_split1.txt
and downloaded the UCF101 split1. when run the given command for training i'm getting following error. I'm new to caffe can you please tell me the steps for training a model. Thank you.

F0513 15:45:57.349095 15471 solver.cpp:440] Cannot write to snapshot prefix './logs_end/vgg16_end'.  Make sure that the directory exists and is writeable.
*** Check failure stack trace: ***
    @     0x7fa4e2e435cd  google::LogMessage::Fail()
    @     0x7fa4e2e45433  google::LogMessage::SendToLog()
    @     0x7fa4e2e4315b  google::LogMessage::Flush()
    @     0x7fa4e2e45e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fa4e376a3ed  caffe::Solver<>::CheckSnapshotWritePermissions()
    @     0x7fa4e376d6c4  caffe::Solver<>::Init()
    @     0x7fa4e376da7a  caffe::Solver<>::Solver()
    @     0x7fa4e34f6ca3  caffe::Creator_SGDSolver<>()
    @           0x40a6e8  train()
    @           0x4075a8  main
    @     0x7fa4e18f7830  __libc_start_main
    @           0x407d19  _start
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by bryanyzhu** [comment]
Hi, the error message is clear. You need to make a directory named "logs_end" in your current working directory to save models. 

The "logs_end" param is set in solver.prototxt. Hope this helps.

**Comment by adimurthi** [comment]
Hi, Thank you so much for the help  that worked for me. but unfortunately i end up with another error. I created one more directory in CD and given path to train_rgb_split1.txt and val_rgb_split1.txt. It is able to open train_rgb_split1.txt but could not load. 


E0514 10:35:32.695055  4299 io.cpp:453] Could not load file /home/adi/Hidden-Two-Stream/models/ucf101_split1_unsup_end/new/WallPushups/v_WallPushups_g21_c06/image_0071.jpg
F0514 10:35:32.695204  4299 multi_frame_data_layer.cpp:65] Check failed: ReadSegmentMultiRGBToDatum(lines_[lines_id_].first, lines_[lines_id_].second, offsets, new_height, new_width, new_length, &datum) 
*** Check failure stack trace: ***
    @     0x7f45dbd985cd  google::LogMessage::Fail()
    @     0x7f45dbd9a433  google::LogMessage::SendToLog()
    @     0x7f45dbd9815b  google::LogMessage::Flush()
    @     0x7f45dbd9ae1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f45dc6606b9  caffe::MultiFrameDataLayer<>::DataLayerSetUp()
    @     0x7f45dc5f6ae3  caffe::BasePrefetchingDataLayer<>::LayerSetUp()
    @     0x7f45dc6b7902  caffe::Net<>::Init()
    @     0x7f45dc6b9121  caffe::Net<>::Net()
    @     0x7f45dc6c139a  caffe::Solver<>::InitTrainNet()
    @     0x7f45dc6c26d7  caffe::Solver<>::Init()
    @     0x7f45dc6c2a7a  caffe::Solver<>::Solver()
    @     0x7f45dc44bca3  caffe::Creator_SGDSolver<>()
    @           0x40a6e8  train()
    @           0x4075a8  main
    @     0x7f45da84c830  __libc_start_main
    @           0x407d19  _start
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by bryanyzhu** [comment]
Hi, according to the error, could you check that if there is indeed an image file in that location (/home/adi/Hidden-Two-Stream/models/ucf101_split1_unsup_end/new/WallPushups/v_WallPushups_g21_c06/image_0071.jpg)? Because it seems that the code couldn't find it. 

One possibility is, we use different video codec to decode the videos. This will lead to different video frames for each video. For example, for this video (v_WallPushups_g21_c06), I may have 71 images, but you may have less than 71 images. So that's why your code could not load the data. To solve the problem, you need to generate your own train_rgb_split1.txt and val_rgb_split1.txt. You can write a simple python script to finish this task, basically just counting how many frames you have.

**Comment by adimurthi** [comment]
Thank you so much for the help. I got almost less than 60 frames per video. if change number of frames in train_rgb_split1.txt and val_rgb_split1.txt will it effect the ground truth class? do i need change anything in testing datasets (UCF101 split 1, UCF101 split 2, UCF103 split 3) since i got different frames numbers for videos.

**Comment by adimurthi** [comment]
Hi, Thank you so much for the help. I got almost less than 60 frames per video. if change number of frames in train_rgb_split1.txt and val_rgb_split1.txt will it effect the ground truth class? do i need change anything in testing datasets (UCF101 split 1, UCF101 split 2, UCF103 split 3) since i got different frames numbers for videos.

**Comment by bryanyzhu** [comment]
It will effect the performance a little bit, but won't be much. You don't need to do anything, just update the train_rgb_split1.txt and val_rgb_split1.txt according to your situation.

**Comment by adimurthi** [comment]
Hi, thanks for your answers. It helped me a lot.

**Comment by ylc2580** [comment]
hello，
     when i use the commond you gave ,When I was training, I made the following mistakes：
I0419 14:34:11.274951  2151 sgd_solver.cpp:106] Iteration 480, lr = 1e-06
I0419 14:36:48.555851  2151 solver.cpp:456] Snapshotting to binary proto file ./logs_end/vgg16_end_iter_500.caffemodel
I0419 14:37:00.028300  2151 sgd_solver.cpp:273] Snapshotting solver state to binary proto file ./logs_end/vgg16_end_iter_500.solverstate
I0419 14:37:04.153931  2151 solver.cpp:338] Iteration 500, Testing net (#0)
F0419 14:37:04.657557  2151 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
    @     0x7f7080db55cd  google::LogMessage::Fail()
    @     0x7f7080db7433  google::LogMessage::SendToLog()
    @     0x7f7080db515b  google::LogMessage::Flush()
    @     0x7f7080db7e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f7081687d20  caffe::SyncedMemory::to_gpu()
    @     0x7f7081686d49  caffe::SyncedMemory::mutable_gpu_data()
    @     0x7f70816a3972  caffe::Blob<>::mutable_gpu_data()
    @     0x7f70816f7bb9  caffe::ScaleLayer<>::Forward_gpu()
    @     0x7f70816b3ec2  caffe::Net<>::ForwardFromTo()
    @     0x7f70816b3fd7  caffe::Net<>::Forward()
    @     0x7f708168e6d2  caffe::Solver<>::Test()
    @     0x7f708168f09e  caffe::Solver<>::TestAll()
    @     0x7f708168f1c2  caffe::Solver<>::Step()
    @     0x7f708168fce9  caffe::Solver<>::Solve()
    @           0x40bb17  train()
    @           0x407724  main
    @     0x7f707f869830  __libc_start_main
    @           0x407ed9  _start
    @              (nil)  (unknown)
[6]    2151 abort (core dumped)  ../../build/tools/caffe train -solver=end_solver.prototxt 
the dataset is ucf and my cuda memory is about 8.1G
