### ISSUE TITLE
information about pre-requisites 

### ISSUE THREAD

**Issue by kamurthianudeep** [bryanyzhu/Hidden-Two-Stream#17]
Hi, Thank you so much for the code. This project is so interesting, i want to implement it on my computer.
my PC specifications:
ubuntu 16.04
cuda 8.0, cudnn 5.1 
nvidia Gtx1060
RAM 16GB.
I installed caffe and compiled. I almost set to start the project. before that, I want to know few things about extracted video frames and is it possible to test real-time action recognition with this project?. I searched for extracted frames in your given repository but I couldn't find any. could you please tell me that where the extracted frames folder in a repository and how these frames relate to lists available in train_rgb_split1.txt.
I think these questions may be basic for you but I am a beginner. I hope you will answer patiently.
thank you.

**Comment by bryanyzhu** [comment]
Hi thanks for your interest in our work. First, yes, you can use it to test real-time action recognition. Second, for the extracted frames, take the first line in train_rgb_split1.txt for example, `FRAME_PATH/WallPushups/v_WallPushups_g21_c06` is the absolute path to the frames of video v_WallPushups_g21_c06. 

More specifically, if you have a video named v_WallPushups_g21_c06.mp4, you can use opencv or ffmpeg to decode the video to frames. Suppose the frames are stored in the directory `/home/user/actions/WallPushups/v_WallPushups_g21_c06`. This directory will be written to the list in 
train_rgb_split1.txt. Hope this is clear.

**Comment by kamurthianudeep** [comment]
Hi, Thanks for the reply. so I need to extract frames from 13000 videos and write to the list in train_rgb_split.txt. I think it takes a lot of time to do for all videos. here i have some doubts first do I need to write a code for something which is not available in the given repository to train the model? second, once I done with extracting frames how much time will it take to train and test the model?

**Comment by bryanyzhu** [comment]
It is not that bad, extracting video frames is very fast. I don't exactly remember the time, but extracting frames from 13000 videos will take you about 2~4 hours. 

Yes, you need to write your own code to extract frames. Different people prefer different ways to decode the videos, that is why I didn't include this step in the repo. If you really don't want to write it, you can refer to [here](https://github.com/yjxiong/temporal-segment-networks/blob/master/tools/build_of.py) for a starter code.

Once you got the frames, it will take you 4 hours to train the spatial model, and 20 hours to train the temporal model.

**Comment by kamurthianudeep** [comment]
Hi, thanks for the help. the given reference link includes extracting motion information too right? In our project, we give the normal frames as input to the MotionNet and motionnet will extract optical information between frames.

**Comment by bryanyzhu** [comment]
yes, it includes extracting motion information. I just want to give you a starter code. We don't need to pre-compute flow here.
