### ISSUE TITLE
libprotobuf WARNING during training

### ISSUE THREAD

**Issue by adimurthi** [bryanyzhu/Hidden-Two-Stream#18]
Hi, as you suggested i created my own train_rgb_split1.txt and val_rgb_split1.txt then i started to train the model, i end up with this following error. could you please help me.

V6
I0520 11:17:13.860306 16923 net.cpp:262] This network produces output accuracy
I0520 11:17:13.860309 16923 net.cpp:262] This network produces output action_loss
I0520 11:17:13.860812 16923 net.cpp:275] Network initialization done.
I0520 11:17:13.862537 16923 solver.cpp:60] Solver scaffolding done.
I0520 11:17:13.870612 16923 caffe.cpp:129] Finetuning from ucf101_split1_vgg16_init.caffemodel
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 708026968
I0520 11:17:15.177098 16923 net.cpp:753] Ignoring source layer input
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 708026968
I0520 11:17:15.739457 16923 net.cpp:753] Ignoring source layer input
I0520 11:17:15.890053 16923 caffe.cpp:219] Starting Optimization
I0520 11:17:15.890076 16923 solver.cpp:280] Solving end_to_end_train
I0520 11:17:15.890079 16923 solver.cpp:281] Learning Rate Policy: multistep
F0520 11:17:16.851193 16923 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
    @     0x7f8d0e62e5cd  google::LogMessage::Fail()
    @     0x7f8d0e630433  google::LogMessage::SendToLog()
    @     0x7f8d0e62e15b  google::LogMessage::Flush()
    @     0x7f8d0e630e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f8d0ef59240  caffe::SyncedMemory::to_gpu()
    @     0x7f8d0ef58209  caffe::SyncedMemory::mutable_gpu_data()
    @     0x7f8d0ed738c3  caffe::Blob<>::mutable_gpu_diff()
    @     0x7f8d0ef7f35f  caffe::CuDNNConvolutionLayer<>::Backward_gpu()
    @     0x7f8d0ed5cfcb  caffe::Net<>::BackwardFromTo()
    @     0x7f8d0ed5d02f  caffe::Net<>::Backward()
    @     0x7f8d0ed505a4  caffe::Solver<>::Step()
    @     0x7f8d0ed51029  caffe::Solver<>::Solve()
    @           0x40b497  train()
    @           0x4075a8  main
    @     0x7f8d0d0e2830  __libc_start_main
    @           0x407d19  _start
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by adimurthi** [comment]
Hi, I changed batch size from 8 to 4 in end_train_val.prototxt and train.prototxt so I am no more getting above error but I am getting another error. 

I0520 21:17:20.379940 25533 layer_factory.hpp:77] Creating layer PhotometricLoss6
I0520 21:17:20.379947 25533 net.cpp:91] Creating Layer PhotometricLoss6
I0520 21:17:20.379952 25533 net.cpp:426] PhotometricLoss6 <- PhotoDifference6
I0520 21:17:20.379958 25533 net.cpp:426] PhotometricLoss6 <- BorderMask6_BorderMask6_0_split_0
I0520 21:17:20.379966 25533 net.cpp:400] PhotometricLoss6 -> PhotometricLoss6
F0520 21:17:20.379981 25533 charbonnier_loss_layer.cpp:23] Check failed: bottom[0]->shape(0) == bottom[1]->shape(0) (4 vs. 8) Mask batch size not the same as input batch size
*** Check failure stack trace: ***
    @     0x7f78602e25cd  google::LogMessage::Fail()
    @     0x7f78602e4433  google::LogMessage::SendToLog()
    @     0x7f78602e215b  google::LogMessage::Flush()
    @     0x7f78602e4e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f7860b14d29  caffe::CharbonnierLossLayer<>::Reshape()
    @     0x7f7860a20951  caffe::Net<>::Init()
    @     0x7f7860a22161  caffe::Net<>::Net()
    @     0x7f7860a01a9a  caffe::Solver<>::InitTrainNet()
    @     0x7f7860a02dd7  caffe::Solver<>::Init()
    @     0x7f7860a0317a  caffe::Solver<>::Solver()
    @     0x7f78609e2a63  caffe::Creator_SGDSolver<>()
    @           0x40a6e8  train()
    @           0x4075a8  main
    @     0x7f785ed96830  __libc_start_main
    @           0x407d19  _start
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by bryanyzhu** [comment]
hi, you are right. Your first error is due to out of memory problem, so reducing batch size is good. 

Your second error is kind of my bad. I hard code the batch size [here](https://github.com/bryanyzhu/Hidden-Two-Stream/blob/master/models/ucf101_split1_unsup_end/end_train_val.prototxt#L241-L442) as well. These are for the bordermask. If you don't understand, it is ok. You just need to change the `dim` parameter from 8 to 4 for all these masks. Then the code should be ok to run.

**Comment by adimurthi** [comment]
Hi, thank you so much that worked for me. but it is throwing another error. is it because i changed batch_size from 16 to 4 in train.prototxt in multiframe_MotionNet?. I don't know the exact reason because sometimes it goes till 100 iterations and sometimes it stops at 20 iterations at every time it throws following error.  could you please tell me how to solve this. thank you.

I0521 13:40:21.494236  6075 sgd_solver.cpp:106] Iteration 20, lr = 1e-06
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 140) > this->size() (which is 0)
*** Aborted at 1526902906 (unix time) try "date -d @1526902906" if you are using GNU date ***
PC: @     0x7f8efbc20428 gsignal
*** SIGABRT (@0x3e8000017bb) received by PID 6075 (TID 0x7f8ea0ffd700) from PID 6075; stack trace: ***
    @     0x7f8efbc204b0 (unknown)
    @     0x7f8efbc20428 gsignal
    @     0x7f8efbc2202a abort
    @     0x7f8efca3484d __gnu_cxx::__verbose_terminate_handler()
    @     0x7f8efca326b6 (unknown)
    @     0x7f8efca32701 std::terminate()
    @     0x7f8efca32919 __cxa_throw
    @     0x7f8efca5b3f7 std::__throw_out_of_range_fmt()
    @     0x7f8ef135b697 cv::GdalDecoder::checkSignature()
    @     0x7f8ef134e917 cv::findDecoder()
    @     0x7f8ef13554f4 cv::imread_()
    @     0x7f8ef1355f59 cv::imread()
    @     0x7f8efd8180f1 caffe::ReadSegmentMultiRGBToDatum()
    @     0x7f8efd94f545 caffe::MultiFrameDataLayer<>::load_batch()
    @     0x7f8efd9e4b0f caffe::BasePrefetchingDataLayer<>::InternalThreadEntry()
    @     0x7f8efda77715 caffe::InternalThread::entry()
    @     0x7f8ef11225d5 (unknown)
    @     0x7f8eeb7616ba start_thread
    @     0x7f8efbcf241d clone
    @                0x0 (unknown)
Aborted (core dumped)

**Comment by adimurthi** [comment]
After getting above error, i tried to run the command again but it is automatically shutting down my laptop. is this the serious error?

**Comment by bryanyzhu** [comment]
Hi, I am sorry I didn't encounter this error before. But it seems that when the image loader try to load a new batch, there is no more images to load anymore. That is why the out of range error occurs. 

So the reason maybe some of your videos have too few frames. For example, you need to have at least 20 frames for a video to make the code work. So please check your train_rgb.txt and eval_rgb.txt file, see if the length of the video are too few. If there is such a video, please delete it. Try it and let me know if the problem still occurs.

**Comment by adimurthi** [comment]
Hi, Thanks for the reply. I checked in both train_rgb_split1.txt and val_rgb_split1.txt there is no video having less than 20 frames. when i tried to run more times my laptop is getting shutdown automatically. one more doubt do i need to generate frames for other two train_rgb_split2.txt, train_rgb_split3.tx and val_rgb_split2.txt, val_rgb_split3.txt in folders ucf101_split2_unsup_end and ucf101_split3_unsup_end?

**Comment by bryanyzhu** [comment]
no, you don't. when you train model on split 1, there is no need to generate files for split2 and split3. 

See this line of the error message:
`what(): basic_string::substr: __pos (which is 140) > this->size() (which is 0)`

I think it means the system try to find the 140th frame in this video, but found that the video size is 0. I still doubt your generated train.txt has some problems. 

To test if I am right, please change line 7 to line 14 in end_train_val.prototxt. 

`multi_frame_data_param {
    source: "./train_rgb_split1.txt"
    batch_size: 8
    new_width: 340
    new_height: 256
    new_length: 11
    num_segments: 1
  }`

to 

`multi_frame_data_param {
    source: "./train_rgb_split1.txt"
    batch_size: 8
    shuffle: False
    new_width: 340
    new_height: 256
    new_length: 11
    num_segments: 1
  }`

I mean, add `shuffle: False' during training phase. In this case, maybe the training will always end at a specific iteration. Then we will know which video is wrong.

**Comment by adimurthi** [comment]
Hi, As you doubted, there are 100s of frames with 0 bytes in size. I found them all and deleted. When tried to train the model, after some iterations pop-up will say goodbye and shutdowns my laptop. Is this because lack of memory?
My Laptop config:
Gtx1060: 6Gb
RAM :16GB
SSD:250GB

**Comment by bryanyzhu** [comment]
Maybe, I also encountered such problem, but long long time ago. At that time, it is because my power supply unit is too small. After some iterations, the system will directly shut down and restart. So either the GPU memory or the PSU is small. Try reduce the batch size to 1 to see if the problem persists.

**Comment by adimurthi** [comment]
Hi, Thank you so much for your help. I reduced batch size to 1 and i trained the model, it took 15 hours to train the model.
I0525 09:55:19.160817  2185 solver.cpp:406]     Test net output #20: accuracy = 0.6375
I0525 09:55:19.160823  2185 solver.cpp:406]     Test net output #21: action_loss = 1.33719 (* 1 = 1.33719 loss)
I0525 09:55:19.160830  2185 solver.cpp:323] Optimization Done.
I0525 09:55:19.161173  2185 caffe.cpp:222] Optimization Done.

**Comment by bryanyzhu** [comment]
Good to know~Cheers. The number also seems reasonable.

**Comment by adimurthi** [comment]
Once again thanks for your support..
