### ISSUE TITLE
confused by the role LRN layer played in the training stage?

### ISSUE THREAD

**Issue by Zealoe** [bryanyzhu/Hidden-Two-Stream#19]
I notice there exist LRN layers in training stage when we calculate loss. But what's the effect of these LRN layers? I think normalization among RGB channels seems unnecessary. Thanks!

**Comment by bryanyzhu** [comment]
It doesn't have a big effect for training the action recognition model. 

But the motivation is coming from this paper, https://arxiv.org/abs/1608.05842. As seen in Section 3.2 of the paper, 

> In initial tests, we noticed that the unsupervised approach had difficulties in regions that were highly saturated or very dark. Adding photometric augmentation compounds this issue by making these regions even less discriminable. To address this issue, we pass the geometrically augmented images directly to the photometric loss prior to photometric augmentation. Further, we apply a local 9 × 9 response normalization to the geometrically augmented images to ameliorate multiplicative lighting factors

So that  is why I adopt LRN layers.
