### ISSUE TITLE
Error While testing

### ISSUE THREAD

**Issue by christofjan** [bryanyzhu/Hidden-Two-Stream#20]
Hi, I'm getting following error while training, this is because i changed batch_size from 50 to 5  due to lack of memory. could you please tell me where do i need to change the shape to get it right. 
net.blobs['data'].data[...] = np.transpose(rgb[:,:,:,span], (3,2,1,0))
ValueError: could not broadcast input array from shape (5,33,224,224) into shape (50,33,224,224)

**Comment by bryanyzhu** [comment]
you mean testing, right? because training batch size is 8. 

If it is testing, then you also need to change [here](https://github.com/bryanyzhu/Hidden-Two-Stream/blob/master/models/ucf101_split1_unsup_end/stack_motionnet_vgg16_deploy.prototxt#L3). I think it will solve your problem.

**Comment by christofjan** [comment]
thanks for the help.

**Comment by ScuAndy** [comment]
By the way, how could I change the batch size(the first input_dim parameter) while training?
