### ISSUE TITLE
how did you suppress background?

### ISSUE THREAD

**Issue by christofjan** [bryanyzhu/Hidden-Two-Stream#22]
Hi,
      With your help i managed to train and test the model properly. Now when i test the model with real time actions it is predicting actions correctly irrespective of the background and objects which i did not understand, could please tell me how you suppressed background and focused only on actions. just i want to know more about approach you used for this operation.   

Thank you..

**Comment by bryanyzhu** [comment]
Hi good to know that. Actually, I didn't do anything specific to suppress the background. But there are two advantages of the two-stream framework. 

1. **The temporal stream**. Optical flow describes what are moving, so it will focus on human motion and suppress the background. 

2. **Deep learning**. I don't know how large your dataset is. But if your performance is good, I suppose your dataset is large enough. So the CNN can learn the class-specific feature by itself. The model will know what are important to recognize the action, what are not. You don't need to do that yourself.

But actually, if you get good results on your data, it maybe your dataset is easy. Some other people also use my framework to do real-time action recognition, but the performance will degrade a lot in places that has lots of water, or lots of human. So I guess maybe your data is clean and large. 

On the other hand, my framework is quite robust and effective, so you should not be too surprised if you can predict actions correctly.

**Comment by christofjan** [comment]
Hi,
           thank you so much for information. I used same dataset (UCF101) which you used, I did not change anything, but i haven't tested on all categories. but whatever i tested it predicted correctly. Here I am confused with code, when we train the model  it will only train MotionNet and Temporal streamNet because architecture defined in the end_train_val.prototxt is only available for MotionNet and Temporal streamNet. I couldn't find code for Spatial network in the repo. in  two stream approach we are passing single frame per video to Spatial network to carry information about scenes and objects right? 
Thank you..

**Comment by bryanyzhu** [comment]
The accuracy for the temporal stream alone is 85%, so you should get most predictions correct, it is expected. 

Yes, I only provide temporal stream code here. You can find the spatial stream code and model [here](https://github.com/yjxiong/caffe/tree/action_recog/models/action_recognition). I didn't change anything for the spatial stream.

**Comment by christofjan** [comment]
thank you so much sir..

**Comment by Mohamad73** [comment]
Hello, is there a code for real time prediction, or you created it?

**Comment by bryanyzhu** [comment]
@Mohamad73 You can refer to this file, 

https://github.com/bryanyzhu/Hidden-Two-Stream/blob/master/models/ucf101_split1_unsup_end/eval_ucf101/demo_hidden.py

This is used for evaluation, but can be changed to predict any videos with minor modifications. 

And it is real-time.
