### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by christofjan** [bryanyzhu/Hidden-Two-Stream#23]
Hi sir, 
          I am ending up with following error when i tried to plot the graphs. 

adi@adi-Inspiron-7577:~/Hidden-Two-Stream/tools/extra$ python plot_training_log.py 1 /home/adi/new1.png model_1_train.log 
Traceback (most recent call last):
  File "plot_training_log.py", line 196, in <module>
    plot_chart(chart_type, path_to_png, path_to_logs)
  File "plot_training_log.py", line 122, in plot_chart
    data = load_data(data_file, x, y)
  File "plot_training_log.py", line 93, in load_data
    data[1].append(float(fields[field_idx1].strip()))
IndexError: list index out of range

I parsed log data into model_1_train.log file and i tried to get train.log and test.log files but i got above error. this error is because of it was not able to read lines after 15000 iterations. so i skipped lines after 15000 iterations. so i solved this error by parsing lines which is having length greater than 4(if len(fields) > 4)
def load_data(data_file, field_idx0, field_idx1):
    data = [[], []]
    with open(data_file, 'r') as f:
        for line in f:
            line = line.strip()
            if line[0] != '#':
                fields = line.split()
                # print "line: " + str(line)
                # print "fields: " + str(fields)
                # print "one: " + str(fields[field_idx0])
                # print "two: " + str(fields[field_idx1])
                 **if len(fields) >= 4:**
                    data[0].append(float(fields[field_idx0].strip()))
                    data[1].append(float(fields[field_idx1].strip()))
    return data

after solving the above error i was able to get train.log and test.log files.
when i ran command `python plot_training_log.py 1 /home/adi/new1.png train.log test.log`  i was getting following error..

Traceback (most recent call last):
  File "/home/adi/Hidden-Two-Stream/tools/extra/extract_seconds.py", line 64, in <module>
    extract_seconds(sys.argv[1], sys.argv[2])
  File "/home/adi/Hidden-Two-Stream/tools/extra/extract_seconds.py", line 49, in extract_seconds
    assert start_datetime, 'Start time not found'
AssertionError: Start time not found
paste: aux4.txt: No such file or directory
rm: cannot remove 'aux4.txt': No such file or directory
Traceback (most recent call last):
  File "/home/adi/Hidden-Two-Stream/tools/extra/extract_seconds.py", line 64, in <module>
    extract_seconds(sys.argv[1], sys.argv[2])
  File "/home/adi/Hidden-Two-Stream/tools/extra/extract_seconds.py", line 49, in extract_seconds
    assert start_datetime, 'Start time not found'
AssertionError: Start time not found
paste: aux3.txt: No such file or directory
rm: cannot remove 'aux3.txt': No such file or directory

but when i ran command `python plot_training_log.py 1 /home/adi/new1.png model_1_train.log` i got following graphs which are absolutely wrong i guess.

![test_accuracy](https://user-images.githubusercontent.com/39825151/41930121-6bd225e6-797a-11e8-8bac-676ad08302a8.png)
![test_loss](https://user-images.githubusercontent.com/39825151/41930133-70aaf520-797a-11e8-8f0b-186ac1ea512b.png)
![test](https://user-images.githubusercontent.com/39825151/41930194-9cf43916-797a-11e8-8c01-1a3c5d10eb42.png)

![train_learning_rate](https://user-images.githubusercontent.com/39825151/41930146-786fd6fe-797a-11e8-95be-5ee0e1f846e7.png)

could you please help me where i did a mistake or do i need to change something to get start time.

thank you..

**Comment by bryanyzhu** [comment]
The training loss figure looks ok, but the test loss figure is definitely wrong. I don't use these python scripts to generate figures, I just use the output in the command line to plot my own figure. So I don't know where goes wrong. I suppose it is some minor bug in the format of your log, maybe there is a mismatching problem. I suggest you write your own scripts to visualize the training progress.

**Comment by bryanyzhu** [comment]
Closed due to lack of activity.
