### ISSUE TITLE
About training question

### ISSUE THREAD

**Issue by Nortinwell** [bryanyzhu/Hidden-Two-Stream#26]
Dear Sir,
During training i meet the question as follow:
```
I0717 14:36:00.550038  2451 layer_factory.hpp:77] Creating layer data
I0717 14:36:00.550062  2451 net.cpp:91] Creating Layer data
I0717 14:36:00.550067  2451 net.cpp:400] data -> data
I0717 14:36:00.550086  2451 net.cpp:400] data -> label
I0717 14:36:00.550129  2451 multi_frame_data_layer.cpp:33] Opening file: /home/zh/Hidden-Two-Stream-master/models/ucf101_split1_unsup_end/train_rgb_split1.txt
I0717 14:36:00.554026  2451 multi_frame_data_layer.cpp:49] A total of 9537 videos.
E0717 14:36:00.554062  2451 io.cpp:453] Could not load file /home/zh/Hidden-Two-Stream-master/UCF-101/WallPushups/v_WallPushups_g21_c06/image_0060.jpg
F0717 14:36:00.554143  2451 multi_frame_data_layer.cpp:65] Check failed: ReadSegmentMultiRGBToDatum(lines_[lines_id_].first, lines_[lines_id_].second, offsets, new_height, new_width, new_length, &datum) 
```
How is the image_0060.jpg generated in this code? and i cannot download your pre-trained models. If it is convenient, can you send it to my email? my email: dingpeng0205@foxmail.com
Thanks!

**Comment by adimurthi** [comment]
Hi, 
     the above code will not generate any images, there is no code in the repository to extract frames from videos. you have to write code to extract frames from videos before training the model. if you already did, then generate your won train_rgb_split1.txt and val_rgb_split1.txt because you may get different number of frames. to extract frames just use OpenCV function. 

Thank you.

**Comment by Nortinwell** [comment]
Thanks for your help! I had extract frames for each video, and it's already training.

**Comment by bryanyzhu** [comment]
@adimurthi Thank you 👍
