### ISSUE TITLE
question about memory 

### ISSUE THREAD

**Issue by huanghuan12** [bryanyzhu/Hidden-Two-Stream#27]
Check failed: error == cudaSuccess (77 vs. 0)  an illegal memory access was encountered
I am using  4 pieces of GTX1080Ti GPU. but there is still an error of "Check failed: error == cudaSuccess (77 vs. 0)  an illegal memory access was encountered".
I searched online for a while. It seems because my GPU runs out of memory and I should decrease the batch_size. But there still was this error though I decreased the batch_size to 1.
I have seen the author used the Titan X GPU. I wonder how much memory this process occupies.

**Comment by adimurthi** [comment]
Hi,
      change the batch size [here](https://github.com/bryanyzhu/Hidden-Two-Stream/blob/master/models/ucf101_split1_unsup_end/end_train_val.prototxt#L241-L442) as well. change `dim`  parameter from 8 to 1 for all the masks.

**Comment by huanghuan12** [comment]
Yes, I have changed both batch_size and dim. But the error still exists. "Check failed: error == cudaSuccess (77 vs. 0) an illegal memory access was encountered"

**Comment by bryanyzhu** [comment]
First, the process occupies 11.6G memory, so you need to reduce batch size to make it work on 1080Ti.

But I don't know the exact solution, because many situations will lead to this error. You could try the following:

1. Try use just one GPU, not 4 together. 
2. Check if you are using cudnn 5.1
3. If you are using cuda < 8, change to cuda8.0.

**Comment by huanghuan12** [comment]
The three attempts can't help me. I wonder you used  Titan X GPU or Titan XP GPU. Because the memory of Titan X GPU is 8G. Did you use two GPUs?

**Comment by bryanyzhu** [comment]
I used Titan X, but I believe those are 12GB GPUs. I tested it on my own workstation (1 GPU) and my server (3 GPUs). The code all works fine. Maybe it is a gpu specific problem as some people said online. I'm sorry I don't know the solution.
