### ISSUE TITLE
rng.hpp:22:79: error: 'RandomGeneratorparameter' does not name a type

### ISSUE THREAD

**Issue by zj10102** [bryanyzhu/Hidden-Two-Stream#3]
Hi, when I downloaded the project and built it，“error: 'RandomGeneratorparameter' does not name a type" was found.   How do I solve it？

**Comment by bryanyzhu** [comment]
Actually I didn't have such problem.

You can refer to this issue [here](https://github.com/lmb-freiburg/flownet2/issues/17). I think it is similar because my code is also kind of built upon initial flownet release. 

Try to add #include "caffe/proto/caffe.pb.h" in file /include/caffe/util/rng.hpp.
