### ISSUE TITLE
the accuracy I get is 69%

### ISSUE THREAD

**Issue by Tylerjoe** [bryanyzhu/Hidden-Two-Stream#30]
I followed the readme to train the model without changing any paramter, but the accuracy I got was about 69% on UCF101-split1, which is much lower than you mentioned in your paper(84.88%).
could you please give me some advices? Thanks!

**Comment by bryanyzhu** [comment]
First, the accuracy you got is during training time. During training, we only pick one frame from each video to do the inference, and sometimes it is not robust. My accuracy 84.88% is during test time. During test, we pick 25 frames per video, and do 10 crop augmentation on these 25 frames to obtain the final score. So usually the test accuracy will be 10+% higher than the training/validation accuracy. As a comparison, my training accuracy is about 72%, so your 69% seems reasonable. 

Second, I use cv2 to decode the video to images, using an image quality of 100. If you use default cv2 or other video decoding to extract the video frames, you will get a lower resolution image than I do. That will decrease the accuracy as well.
