### ISSUE TITLE
Training Motion Net

### ISSUE THREAD

**Issue by minhnova** [bryanyzhu/Hidden-Two-Stream#31]
Hi Bryan,

Thank you so much for your great work.
I 've read your paper and I'm trying to follow your implementation.
I have a few quick questions:

1.  Whats the purpose of the file generate_flow_for_ucf101.py? How can I use it for training the MotionNet from scratch (If possible, could you please provide instructions for training MotionNet)?

2. In your paper, you mentioned about stacking MotionNet with a Temporal Stream, that means stacking 2 Caffe models file. How can we do it? 

Best regards,
John Huang

**Comment by bryanyzhu** [comment]
Hi, thank you for your interest. 

1. `generate_flow_for_ucf101.py` is a file for you to generate optical flow offline using MotionNet. It is not for training, but deploying. 

2. To train MotionNet, you just need to run something like this:
```
../../build/tools/caffe train -solver=solver.prototxt
```

3. For combining two or more caffe models, you can refer to [here](https://github.com/BVLC/caffe/blob/master/examples/net_surgery.ipynb). Basically, you need three prototxt file, one for model1, one for model2, and one for the new model. Then you load model1, then load model2, and copy the weights to model3, and the save model3. You can search online how to do it, like how to combine two caffe models.

**Comment by minhnova** [comment]
Hi Sir,
Thank you so much for your help. That’s really kind of you
I can train the MotionNet now. Im working on merging the two models.

Best,
