### ISSUE TITLE
Error while running demo_hidden.py 

### ISSUE THREAD

**Issue by MILOTIDE** [bryanyzhu/Hidden-Two-Stream#35]
Hello,thanks for your sharing.Here I got an error while running demo_hidden.py:
we got 3783 test videos
/home/user/UCF101/ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01
img_file is /home/user/UCF101/ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01/image_0001.jpg
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/imgproc/src/resize.cpp, line 3939
Traceback (most recent call last):
  File "demo_hidden.py", line 87, in <module>
    main()
  File "demo_hidden.py", line 61, in main
    start_frame)
  File "/home/user/workspace/action_recognition/Hidden-Two-Stream-master/models/ucf101_split1_unsup_end/eval_ucf101/HiddenTemporalPrediction.py", line 39, in HiddenTemporalPrediction
    img = cv2.resize(img, dims[1::-1])
cv2.error: /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/imgproc/src/resize.cpp:3939: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize
 
 I have changed the FRAME_PATH in testlist01_with_labels.txt like:
    /home/user/UCF101/ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01 1 
    /home/user/UCF101/ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c02 1 
    /home/user/UCF101/ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c03 1 
It seems it can't find the frame,and I print the img_file  in HiddenTemporalPrediction.py, it prints:
 /home/user/UCF101/ApplyEyeMakeup/v_ApplyEyeMakeup_g01_c01/image_0001.jpg
however i only have v_ApplyEyeMakeup_g01_c01.avi rather than v_ApplyEyeMakeup_g01_c01/image_0001.jpg. So how can I get the image_0001.jpg?
Thanks.Waiting for your reply.

**Comment by bryanyzhu** [comment]
Hi, UCF101 only provide videos, like those .avi. But we need to extract frames first from the videos. You can use either FFmpeg to do that or using cv2. I suggest you use cv2. There is a function called cv2.videoCapture(), which can decode the video to frames. You can search to see how to use that. 

I also have a script to help you do that, it is [at here](https://github.com/bryanyzhu/two-stream-pytorch#data-preparation). The code should be easy to follow. Let me know if you have other problems.

**Comment by MILOTIDE** [comment]
Hello, I tried to install the dense_flow,how ever it errorred as:
dense_warp_flow_gpu.cpp:(.text+0x221c): undefined reference to `cv::xfeatures2d::SURF::create(double, int, int, bool, bool)'
dense_warp_flow_gpu.cpp:(.text+0x2270): undefined reference to `cv::xfeatures2d::SURF::create(double, int, int, bool, bool)'
collect2: error: ld returned 1 exit status
I have installed the opencv-3.1 with contrib module. In the opencv-3.1.0/modules/ I can find xfeatures2d, but in the opencv-3.1.0/build/lib/,I can't find the libopencv_xfeatures2d.so. Does it mean I didn't successfully install the contrib module? However I have tried several times to install the opencv-3.1.0 with opencv_contrib-3.1.0 followed the https://github.com/opencv/opencv_contrib/blob/3.1.0/README.md.
So what should I do to solve the problem?Thanks.

**Comment by MILOTIDE** [comment]
Hello, I have extracted frames from videos using the script you privide,the frames look like img00001,img00002......img00125.... When I run the demo_hidden.py,it searched for img00000 after the img00011,however there is not img00000 extracted. Is the format of the frames wrong? By the way, I don't understand the code:
      for i in range(num_samples):
           stacked_list = []
           stacked_flip_list = []
         for j in range(stacked_frames):
            img_file = os.path.join(vid_name, 'img_{0:05d}.jpg'.format(i*step+j+1 + start_frame))
            img = cv2.imread(img_file, cv2.IMREAD_UNCHANGED)
            img = cv2.resize(img, dims[1::-1])
            stacked_list.append(img)
            stacked_flip_list.append(img[:,::-1,:])
What do the num_samples(25) and the stacked_frames(11)  mean? If I use the cv2 to extract frames to test a steaming video, does that mean I should use a buffer to store 25*11 frames from the video?

**Comment by MILOTIDE** [comment]
Hello, I have extracted frames from videos using the script you privide,the frames look like img00001,img00002......img00125.... When I run the demo_hidden.py,it searched for img00000 after the img00011,however there is not img00000 extracted. Are the names of the frames i extracted wrong? By the way, I don't understand the code of HiddenTemporalPrediction.py
                              for i in range(num_samples):
        stacked_list = []
        stacked_flip_list = []
        for j in range(stacked_frames):
            img_file = os.path.join(vid_name, 'img_{0:05d}.jpg'.format(i*step+j+1 + start_frame))
            img = cv2.imread(img_file, cv2.IMREAD_UNCHANGED)
            img = cv2.resize(img, dims[1::-1])
            stacked_list.append(img)
            stacked_flip_list.append(img[:,::-1,:])
        stacked_img = np.concatenate(stacked_list, axis=2)
        stacked_flip_img = np.concatenate(stacked_flip_list, axis=2)
        rgb[:,:,:,i] = stacked_img
        rgb_flip[:,:,:,i] = stacked_flip_img

What do the num_samples(25) and the stacked_frames(11) mean? If I use the cv2 to extract frames to test a steaming video, does that mean I should use a buffer to store 275 frames from the video?

**Comment by bryanyzhu** [comment]
Hi , sorry for the late reply. 

1. The format is specified as `'img_{0:05d}.jpg'`, which means it should look like img_00001.jpg. So you need to extract them again.

2. num_samples = 25 means for each video, we uniformly sample 25 frames from it to do the evaluation. For example, if you have a video with 250 frames, then you will sample 1, 11, 21, 31, ..., 241 to get the results. 

3. stacked_frames = 11 means we are processing a video clip, not a single frame. Because the input to temporal stream is optical flow. Most people choose 10 optical flow images, so for fair comparison, we also use 10 optical flow images. In order to get 10 flow images, you need 11 frames. Because flow describes motion between two frames. 

4. For streaming video, I don't think you need to store all the frames. You just store the sampled frames.

**Comment by MILOTIDE** [comment]
Thank you very much for your reply. I met another error. When I run the demo_hidden.py, my system automatically reboot when the code running to net.forward . And the same problem happens when I run the spatial_demo.py of the two-stream-pytorch.I can run other network correctly using caffe.  So I really don't know why, maybe this is the cuda or hardware error?

**Comment by bryanyzhu** [comment]
Yeah, maybe cuda issue. 

But try reduce batch size first, there is a possibility that the memory doesn't hold. Change batch size to 5 in [here](https://github.com/bryanyzhu/Hidden-Two-Stream/blob/master/models/ucf101_split1_unsup_end/eval_ucf101/HiddenTemporalPrediction.py#L69) and [here](https://github.com/bryanyzhu/Hidden-Two-Stream/blob/master/models/ucf101_split1_unsup_end/stack_motionnet_vgg16_deploy.prototxt#L3). 

I have encountered this system reboot issue long time ago, and mine was caused by not enough power for GPU. I reduced the batch size and the problem was solved. And later I changed a power supply unit.

**Comment by MILOTIDE** [comment]
Thank you, the reboot is because  the power is not enough.Thanks for your patience.
