### ISSUE TITLE
out of memory while testing

### ISSUE THREAD

**Issue by ScuAndy** [bryanyzhu/Hidden-Two-Stream#38]
I'm using GTX 1080 and ran out of memory while training, and I solved it by reducing batch size from 8 to 4. But I still run out of memory while testing, so is there any ways to cut batch size in testing?

**Comment by bryanyzhu** [comment]
change the 50 to 25 in these two lines, you will be fine. 

https://github.com/bryanyzhu/Hidden-Two-Stream/blob/master/models/ucf101_split1_unsup_end/eval_ucf101/HiddenTemporalPrediction.py#L69

and 

https://github.com/bryanyzhu/Hidden-Two-Stream/blob/master/models/ucf101_split1_unsup_end/stack_motionnet_vgg16_deploy.prototxt#L3

The number need to be a multiple of 25, so 25 is the smallest batch size. I don't know where batch size = 8 comes from.

**Comment by ScuAndy** [comment]
It definitely solved my problem. Thank you for help!
