### ISSUE TITLE
where is the spatial stream cnn?

### ISSUE THREAD

**Issue by jesszgc** [bryanyzhu/Hidden-Two-Stream#39]
hello @bryanyzhu ,
      Thanks for your sharing. But your code bring me a lot confusion. 
1,in demo_hidden.py, it writes  a lot of "spatial" words, but it is for Motionnet and Temporal Stream CNN ;
2, for late Fusion, i can not find any code to genenrate "spatial_quality100_split1.mat" and "temporal_hidden_split1.mat" files,can you help me ?
3, what about the speed? to test the stack_motionnet_vgg16 model, it is very slow on 2.4G CPU and titan X GPU, about 60s for each video,even 1400s

**Comment by bryanyzhu** [comment]
Hi @jesszgc , thank you for your interest in our code. 

1. Yes, it is confusing. Sorry for not cleaning up the code, I adapt it from `demo_spatial.py`, so a lot of naming is still spatial. But it actually means temporal. 

2. When you finished running `demo_spatial.py` and `demo_hidden.py`. You will generate those .mat files, like [here](https://github.com/bryanyzhu/Hidden-Two-Stream/blob/master/models/ucf101_split1_unsup_end/eval_ucf101/demo_hidden.py#L83). Although the names may be different. 

3. My speed in the paper is fps (frame per second), which means the time taken for one frame to go through the network, not the whole video. When you do the evaluation for the whole video, you actually sample 25 frames for each video and do 10-crop for each frame. It means you actually pass 250 frames to the network to process. So you need to divide your time by 250 to get the actual timing. Besides, there are other operations in the `demo.hidden.py` which also costs time.

**Comment by bryanyzhu** [comment]
And for your second question, actually I have those .mat files here,

https://github.com/bryanyzhu/Hidden-Two-Stream/tree/master/test

You can check them out, hope this helps.

**Comment by jesszgc** [comment]
hi @bryanyzhu , thanks for your reply,
    we cannot be satisfied with your understanding of fps. for the whole video we only sampled 25 frames. even though we passed 250 frames to the network, we do only processed 25 frames. 10-crop operation is still for one frame. So we can only divide my time by 25 to get the actual timing.  what do you think?

**Comment by bryanyzhu** [comment]
@jesszgc Good point. But as long as you keep it consistent when you compare different methods, I think it's fine.

**Comment by bryanyzhu** [comment]
Close the issue now due to inactive.
