### ISSUE TITLE
about compile

### ISSUE THREAD

**Issue by ylc2580** [bryanyzhu/Hidden-Two-Stream#40]
hi,
   when i compile the makefile,there are some errors occurs that can not find the file or the directory of examples,but i can find any file or directory in your project.
   I hope to get your help.thanks!

**Comment by bryanyzhu** [comment]
Could you post more details, like which step you are doing, and what are the errors?

**Comment by ylc2580** [comment]
cp Makefile.config.example Makefile.config
➜  Hidden-Two-Stream-master make -j 10 all                            
matlab/+caffe/private python/caffe src/gtest src/caffe src/caffe/layers src/caffe/solvers src/caffe/util src/caffe/test src/caffe/proto tools
find: `examples': 没有那个文件或目录
find: `examples': 没有那个文件或目录
find: `examples': 没有那个文件或目录
PROTOC src/caffe/proto/caffe.proto
CXX src/caffe/layers/lstm_layer.cpp
CXX src/caffe/layers/cudnn_tanh_layer.cpp
CXX src/caffe/layers/power_file_layer.cpp
CXX src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp
CXX src/caffe/layers/imgwriter_layer.cpp
CXX src/caffe/layers/parameter_layer.cpp
CXX src/caffe/layers/im2col_layer.cpp
CXX src/caffe/layers/input_layer.cpp
CXX src/caffe/layers/neg_relu_layer.cpp
CXX src/caffe/layers/silence_layer.cpp
In file included from ./include/caffe/layer.hpp:8:0,
                 from src/caffe/layers/neg_relu_layer.cpp:4:
./include/caffe/blob.hpp:9:34: fatal error: caffe/proto/caffe.pb.h: 没有那个文件或目录
compilation terminated.
Makefile:576: recipe for target '.build_release/src/caffe/layers/neg_relu_layer.o' failed
In file included from src/caffe/layers/lstm_layer.cpp:4:0:
./include/caffe/blob.hpp:9:34: fatal error: caffe/proto/caffe.pb.h: 没有那个文件或目录
compilation terminated.
make: *** [.build_release/src/caffe/layers/neg_relu_layer.o] Error 1

it is my errors。is it for my caffee config?
thanks

**Comment by bryanyzhu** [comment]
I think the error is due to this file is missing, `./include/caffe/blob.hpp:9:34: fatal error: caffe/proto/caffe.pb.h` So please refer to the following thread, the problem should be solved.

https://github.com/muupan/dqn-in-the-caffe/issues/3#issuecomment-70795202

**Comment by ylc2580** [comment]
thanks for your reply.now it had following errors (my opencv version is 3.4.3,cuda is 9.0.and my opencv was not compiled by cuda)
    (1)for my first use caffe and careless,my first false step is use  the commond that "cp  example nakefile.config makefile.confiug",this maybe change your right config.
    (2)maybe there need some changes in makefile for rigtht hdf5 path. my changes is "LIBRARIES += glog gflags protobuf boost_system boost_filesystem m hdf5_serial_hl hdf5_serial"
    (3)when i compile your project,i must use cudnn.hpp which is from other compiled caffe (path is master\include\caffe\util\) to replace yours, and then it could work,otherwise it will occur errors.
    (4)because my cuda version is 9.0,when i do this,it occurs "make: *** [.build_release/cuda/src/caffe/util/im2col.o] Error 1",then we should change your makefile.config file in 28 lines to match cuda version.
    (5)maybe must use -std=c++11.
    (7)i must change my opencv 3rdpart lib path in your makefile.config
    (6)when i do this ,it occus errors:
	src/caffe/layers/resample_layer.cu:11:34: fatal error: opencv2/cudaarithm.hpp: 没有那个文件或目录
	compilation terminated.
	Makefile:604: recipe for target '.build_release/cuda/src/caffe/layers/resample_layer.o' failed.
    it may because my compiled opencv. could you tell me your opencv version ,cuda version and whether your opencv is compiled by cuda? then i will try.
    thanks.

**Comment by bryanyzhu** [comment]
This project is developed late 2016. My opencv version is 3.2.0. cuda version is 7.5 and my opencv is compiled by cuda. 

I vaguely remember this error, I think it is because you didn't compile your opencv with cuda. Hope this helps.

**Comment by bryanyzhu** [comment]
Close for now due to inactivity.
