### ISSUE TITLE
dataset problem

### ISSUE THREAD

**Issue by jqsun98** [bryanyzhu/Hidden-Two-Stream#43]
hello, @bryanyzhu 
Thanks for your sharing!
I am an undergraduate and I'm working on my graduation project but I don't have enough GPU and memory to extract images. So could you share your data with me through cloud? I'd like to have RGB frames and optical flow images of UCF101. Thank you!

**Comment by bryanyzhu** [comment]
I'm sorry I don't have those at this moment.
