### ISSUE TITLE
Two-frame MotionNet

### ISSUE THREAD

**Issue by ParitoshParmar** [bryanyzhu/Hidden-Two-Stream#5]
Hi Yi,

Amazing work and thanks a ton for the code. Just a question, to replicate the MotionNet (2-frame) experiment as mentioned in Table III of your paper, do we need to just change `new_length` from 11 to 2 (and surely, wherever it affects) ? Or do we need to change other parameters such as, no. of filters in 'Convolution' layers ?

Cheers!

**Comment by bryanyzhu** [comment]
Thank you. As far as I can recall, you only need to change new_length to 2, others remain the same.
