### ISSUE TITLE
which mean_file should i set when i use motionnet to process grey images?

### ISSUE THREAD

**Issue by Zealoe** [bryanyzhu/Hidden-Two-Stream#8]
When i use generate_flow_for_ucf101.py to process my own data to get flow images, i don't know what value of 'mean_file' should i set if i feed the network with grey images. 
could you please give me some clues?

**Comment by bryanyzhu** [comment]
Hi if it is grey image, then just use 128 as the mean value. It should work.

**Comment by Zealoe** [comment]
thanks for your reply!
